name: Python Tests

on:
  pull_request:
    branches: [main]

jobs:
  run-python-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Start containers
        run: |
          docker-compose up -d --build

      - name: Run tests
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: |
          docker-compose exec -T api python -m pytest "src/tests"

      - name: Stop containers
        if: always()
        run: docker-compose down
